agent-creation
emasquil/ppo pull request #6
Opened 2022-03-01 23:07 UTC by nviolante25

# Agent

- [ ] Crate Agent class to interact with the environment

2022-03-03 11:45 UTC, emasquil requested changes
Please rename the directory to `ppo` and after merging #4 rebase this and we can then merge it

2022-03-06 12:26 UTC, theovincent requested changes

2022-03-06 12:26 UTC, theovincent commented on ppo/agent/agent.py
> +from env_wrapper.pendulum_wrapper import PendulumEnv
I think it should be:
```
from ppo.env_wrapper.pendulum_wrapper import PendulumEnv
```

2022-03-06 12:26 UTC, theovincent commented on ppo/agent/agent.py
> +from networks import PolicyNetwork
I think it should be:
```
from ppo.networks import PolicyNetwork
```

2022-03-07 01:24 UTC, emasquil commented
this became outdated respect to the new PR #12

2022-03-07 01:24 UTC, closed without merging